const tips = [
  // 💼 Career & Job Opportunities
  "Update your LinkedIn profile today — recruiters search for students daily.",
  "Apply to internships 3–6 months before the start date, not last minute.",
  "Follow 10 companies you want to work for on LinkedIn right now.",
  "Message 2 alumni per week on LinkedIn — most people love helping students.",
  "Build a portfolio website with even 2–3 projects — it sets you apart immediately.",
  "Attend at least one career fair per semester, even if you're not job-hunting yet.",
  "Write a new version of your resume for every job application you send.",
  "Apply to jobs even if you don't meet 100% of the requirements — apply anyway.",
  "Use Glassdoor to research salaries before any interview or offer.",
  "Set a Google Alert for your target companies to always have fresh talking points.",
  "Contribute to open source projects — it's a live resume that speaks for itself.",
  "Email the hiring manager directly after applying — 80% of people don't do this.",
  "Practice your answer to 'Tell me about yourself' until it takes exactly 90 seconds.",
  "Your first job doesn't define your career — getting in the door matters most.",
  "Join campus placement cells and show up to every mock interview session.",

  // 🌐 Networking
  "Your network is your net worth — spend 15 minutes a week growing it intentionally.",
  "Send a personalized connection request, never the default LinkedIn message.",
  "Attend hackathons — you meet your future teammates and employers there.",
  "Join professional communities on Discord and Slack in your field.",
  "Follow thought leaders in your industry and engage with their posts genuinely.",
  "Offer value before asking for favors — share articles, give feedback, introduce people.",
  "Keep a simple spreadsheet of every professional contact you make.",
  "Ask for informational interviews — most professionals will say yes to a 20-minute chat.",
  "Stay in touch with professors — they often know about opportunities before anyone else.",
  "Join a student chapter of a professional organization in your field.",

  // 💻 Tech & Digital Skills
  "Learn Git and GitHub — it's non-negotiable in almost every tech or data career.",
  "Build one side project per semester, no matter how small.",
  "Learn SQL — it's the most universally useful technical skill across all industries.",
  "Take one free online course per month on Coursera, edX, or YouTube.",
  "Get familiar with AI tools like ChatGPT and Claude — they're your new productivity layer.",
  "Learn to touch type — even a small speed increase saves hours every year.",
  "Master Excel or Google Sheets — most office jobs rely on it every single day.",
  "Create a GitHub profile and push something to it every week.",
  "Learn one scripting language (Python or JavaScript) — it opens every door.",
  "Build in public — share your projects on social media as you create them.",

  // 🗣️ Communication & Soft Skills
  "Write one email a day to practice professional communication.",
  "Join your college debate club or public speaking group — confidence is a career skill.",
  "Read one non-fiction book per month and write a 3-sentence summary of what you learned.",
  "Practice saying 'I don't know, but I'll find out' — it earns more respect than bluffing.",
  "Give constructive feedback to peers — it sharpens your own thinking too.",
  "Learn to write concisely — cut every email by 30% before sending.",
  "Volunteer to present in class — every awkward rep makes the next one easier.",
  "Ask better questions — a sharp question impresses more than a long answer.",
  "Learn the difference between assertive and aggressive communication.",
  "Summarize every meeting or group project session in writing immediately after.",

  // 🧘 Mental Health & Wellbeing
  "Sleep 7–8 hours. No amount of caffeine replaces the memory boost from proper sleep.",
  "Take a 10-minute walk between study sessions — your focus will return 30% stronger.",
  "Write down 3 things you're grateful for every morning — it rewires your focus.",
  "Talk to a counselor or mentor when you're overwhelmed — asking for help is strength.",
  "Batch your social media usage into one 20-minute slot per day.",
  "Protect your mornings — don't check your phone for the first 30 minutes after waking.",
  "Set a 'worry window' — a 15-minute slot where you're allowed to stress, then move on.",
  "Exercise 3 times a week minimum — it directly boosts memory and mental clarity.",
  "Burnout is real. Schedule rest the same way you schedule study.",
  "Say no to things that don't align with your goals — your time is your most finite resource.",

  // 💰 Finance & Money
  "Open a savings account today and automate transferring even ₹500/month into it.",
  "Track every rupee you spend for one month — awareness is the first step to control.",
  "Learn the difference between a want and a need before every purchase.",
  "Start a small SIP (Systematic Investment Plan) in a mutual fund — even ₹100/month compounds.",
  "Never take on debt for lifestyle expenses — only for investments in your future.",
  "Use UPI and budgeting apps to see where your money actually goes.",
  "Learn what compound interest really means — then use it for you, not against you.",
  "Avoid credit card debt — the interest rates are designed to trap you.",
  "Your financial habits at 20 become your financial reality at 30.",
  "Learn to negotiate — your first salary sets the base for the next 10 years.",

  // 🚀 Productivity & Habits
  "Plan tomorrow's top 3 tasks every night before bed.",
  "Do the task you're avoiding first — it drains more energy as a pending item.",
  "Use a single trusted to-do system and stop re-inventing your workflow every week.",
  "Batch similar tasks together — check emails twice a day, not 40 times.",
  "Create a consistent morning routine — structure eliminates decision fatigue.",
  "Review your week every Sunday: what worked, what didn't, what to adjust.",
  "Identity-based habits work better — say 'I am a reader' not 'I want to read more.'",
  "Remove friction from good habits — put your book on your pillow, not on a shelf.",
  "Track your habits visually — the streak you don't want to break is a powerful motivator.",
  "Start with 2 minutes — every big habit starts embarrassingly small.",

  // 🎯 Goals & Mindset
  "Write your 1-year, 5-year, and 10-year goals. Revisit them every quarter.",
  "Stop waiting to feel motivated — action creates motivation, not the other way around.",
  "Compare yourself only to who you were yesterday, not to others.",
  "Embrace failure as data — every mistake tells you exactly what to fix.",
  "Read one biography per year of someone who built something great.",
  "Discomfort is a signal you're growing — seek it, don't avoid it.",
  "The people you spend the most time with determine your trajectory.",
  "A fixed mindset says 'I'm not smart.' A growth mindset says 'I'm not smart yet.'",
  "Skills compound — every hour you invest in learning returns dividends for decades.",
  "You don't rise to your goals. You fall to the level of your systems.",

  // 🌍 Personal Branding
  "Post one thing you've learned every week on LinkedIn — consistency builds authority.",
  "Your online presence is your 24/7 job application — curate it intentionally.",
  "Write about your projects and learnings — writing clarifies your own thinking.",
  "A strong personal brand means opportunities come to you, not the other way around.",
  "Volunteer for visible roles — leading a college event goes on your resume and your reputation.",
];